version: "3.8"

services: 
    web:
        build: image/nginx
        volumes:
            - ./www/backend:/www/backend
            # - ./www/backend/project2:/www/backend/project2
        ports:
            - 8001:8001
            - 8002:8002
        links:
            - project1
            - project2

    project1:
        build: image/php
        volumes:
            - ./www/backend/project1:/www/backend/project1

    
    project2:
        build: image/php
        volumes:
            - ./www/backend/project2:/www/backend/project2
